title: Yun Codes
author: Yun
email: this.jiyun@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Programmar, Rock climbers, ESL instructor, Freelance writer and part-time sourdough baker... 
  In general, I am just someone who is guided by her curiosity and to see where it goes.
# social links

github_username: actuallyyun # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
